spring:
  data:
    mongodb:
      username: user
      password: user
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*' # Allow all packages to be deserialized not in production
        spring.json.type.mapping: orderConfirmation:com.tengo.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.tengo.ecommerce.notification.PaymentNotificationRequest
server:
  port: 8040

mail:
  host: localhost
  port: 1025
  username: admin
  password: admin
  properties:
    mail:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
